version: "3"
services:
 db:
   image: mysql:5.7
   ports:
     - 13306:3306
   tmpfs:
     - /var/lib/mysql
   volumes:
     - ./initdb.d:/docker-entrypoint-initdb.d
   environment:
     MYSQL_ROOT_PASSWORD: test